---
sudo: false

language: python
python:
  - "3"

cache: pip

before_install:
  - sudo apt-get -qq update

install:
  - pip install mkdocs

script:
  - mkdocs build

deploy:
  provider: pages
  repo: jhughes01/jhughes01.github.io
  local-dir: site
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master